config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'sessions#new'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'

  resources :users, only: %i[edit update]
  resources :passwords, except: :delete, param: :reset_password_token
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  before_create :assign_username

  private

  def assign_username
    self.username = email.split('@').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user])
  end

  def sign_in(user, notification_message = 'Signed in')
    session[:user] = user.id

    redirect_to edit_user_path(user), notice: notification_message
  end
end

app/controllers/passwords_controller.rb
# frozen_string_literal: true

class PasswordsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: user_params[:email])

    flash[:notice] = 'Reset password token sent'

    Passwords::GenerateResetToken.call(@user)

    redirect_back(fallback_location: root_path)
  end

  def edit
  end

  def update
    @form = ResetPasswordForm.new(User.find_by(reset_password_token: params[:reset_password_token]))

    if @form.validate(user_params)
      @form.save

      redirect_to root_path, notice: 'Password changed'
    else
      flash[:error] = @form.errors.full_messages

      redirect_back(fallback_location: root_path)
    end
  end

  private

  def user_params
    params[:user]
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < ApplicationController
  def new
    @form = RegistrationForm.new(User.new)
  end

  def create
    @form = RegistrationForm.new(User.new)

    if @form.validate(params[:user])
      @form.save
      user = @form.sync

      WelcomeMailer.send_welcome_mail(user).deliver_now

      sign_in(user, 'Sign up successfully')
    else
      flash[:error] = @form.errors.full_messages

      render(:new)
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    redirect_to edit_user_path(current_user.id) if current_user
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    user_authentication = Sessions::AuthenticateUser.call(@user, params[:user])

    if user_authentication.authenticated?
      sign_in(@user)
    else
      flash[:error] = user_authentication.error_message

      Sessions::LockUser.call(@user) if @user

      render(:new)
    end
  end

  def destroy
    session[:user] = nil if current_user

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :check_edit_permission

  def edit
    form
  end

  def update
    if form.validate(params[:user])
      flash[:notice] = 'Updated successfully'

      form.save
    else
      flash[:error] = form.errors.full_messages
    end

    redirect_to edit_user_path(form.model)
  end

  private

  def form
    @form ||= UpdateUserForm.new(User.find_by(id: params[:id]))
  end

  def check_edit_permission
    if current_user != form.model
      flash[:error] = 'You are not allowed to perform this action'

      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    messages = flash[:notice] || flash[:error]
    flash_messageg_classes = { notice: 'success', error: 'danger' }

    if flash.any?
      tag.div(class: "alert alert-#{flash_messageg_classes[flash.keys.first.to_sym]}") do
        if messages.is_a?(String)
          tag.li(messages)
        else
          messages.collect { |message| concat(tag.li(message)) }
        end
      end
    end
  end
end

app/views/layouts/_shared_links.html.erb
<% case params[:controller] %>
<% when 'sessions' %>
  <%= button_to 'Sign Up', sign_up_path, class: 'btn btn-outline-info mt-1', method: 'get' %>
  <%= button_to 'Forgot Password', new_password_path, class: 'btn btn-outline-info mt-1', method: 'get' %>
<% when 'passwords' %>
  <%= button_to "Sign In", sign_in_path, class: 'btn btn-outline-info mt-1', method: 'get' %>
  <%= button_to 'Sign Up', sign_up_path, class: 'btn btn-outline-info mt-1', method: 'get' %>
<% when 'registrations' %>
  <%= button_to "Sign In", sign_in_path, class: 'btn btn-outline-info mt-1', method: 'get' %>
  <%= button_to 'Forgot Password', new_password_path, class: 'btn btn-outline-info mt-1', method: 'get' %>
<% when 'users' %>
  <%= button_to 'Sign Out', sign_out_path, class: 'btn btn-outline-info mt-1', method: 'delete' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IncubitTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= flash_messages %>
    <%= yield %>
    <%= render partial: 'layouts/shared_links' %>
  </body>
</html>

app/views/users/edit.html.erb
<p class="text-start fs-1">Edit</p>
<%= simple_form_for @form, as: :user, url: user_path, method: 'put' do |f| %>
  <%= f.input :email, input_html: { readonly: true } %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <%= f.submit 'Update', class: 'btn btn-outline-primary mt-1' %>
<% end %>